# Generated by Django 3.1.7 on 2021-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210306_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
