# Generated by Django 3.1.7 on 2021-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20210308_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show_divider_after_this_item',
            field=models.BooleanField(default=False, help_text='Add a dividing line after this menu item.'),
        ),
    ]
