# Generated by Django 3.1.7 on 2021-03-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20210308_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='show_divider_after_this_item',
        ),
    ]
