# Generated by Django 3.1.7 on 2021-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20210308_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmenuitem',
            name='menu_display_order',
            field=models.IntegerField(default=0, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='menu_display_order',
            field=models.IntegerField(default=0, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='show_divider_after_this_item',
            field=models.BooleanField(default=False, help_text='Add a dividing line after this menu item if on a dropdown menu.'),
        ),
    ]
