# Generated by Django 3.1.7 on 2021-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20210308_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='title_of_submenu',
            field=models.CharField(choices=[('main', 'main'), ('test', 'Test'), ('subtest', 'Sub Test'), ('drop-test', 'Drop Test')], help_text='Enter the menu-ID that this sub-menu will load', max_length=50, null=True),
        ),
    ]
