# Generated by Django 3.1.7 on 2021-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20210310_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='title',
        ),
    ]
