# Generated by Django 3.1.7 on 2021-03-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('menu', '0017_auto_20210310_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Optional image to display if submenu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='display_option',
            field=models.CharField(choices=[('both', 'Icon & Title'), ('text', 'Title Only'), ('icon', 'Icon Only')], default='always', help_text='Determines if menu item is only shown if user logged in, logged out or always', max_length=4),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Title will be used if this is a submenu', max_length=50),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='title_of_submenu',
            field=models.CharField(choices=[('main', 'main'), ('test-sub-menu', 'Test Sub Menu')], help_text='Enter the menu-ID that this sub-menu will load', max_length=50, null=True),
        ),
    ]
