# Generated by Django 3.1.7 on 2021-03-11 15:16

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('menu', '0018_auto_20210310_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='display_option',
            field=models.CharField(choices=[('both', 'Icon & Title'), ('text', 'Title Only'), ('icon', 'Icon Only')], default='text', help_text='Display the sub-menu as icon, text or both.', max_length=4),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='title_of_submenu',
            field=models.CharField(choices=[('header', 'Header'), ('blog', 'Blog')], help_text='Enter the menu-ID that this sub-menu will load', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AutofillMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('show_when', models.CharField(choices=[('always', 'Always'), ('logged_in', 'When logged in'), ('not_logged_in', 'When not logged in')], default='always', help_text='Determines if menu item is only shown if user logged in, logged out or always', max_length=15)),
                ('show_divider_after_this_item', models.BooleanField(default=False, help_text='Add a dividing line after this menu item if on a dropdown menu.')),
                ('menu_display_order', models.IntegerField(default=0, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number')),
                ('description', models.CharField(blank=True, help_text='Optional field to describe what this item will load', max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, help_text='If using link page, any text here will be appended to the page url. For an internal url without page link, leave off the language specific part of the url (ie /accounts/ not /en/accounts/).', max_length=500, null=True)),
                ('max_items', models.IntegerField(default=4, help_text='Maximum results to display in the menu')),
                ('order_by', models.CharField(choices=[('-last_published_at', 'Newest (by most recently updated'), ('-first_published_at', 'Newest to Oldest (by date originally published'), ('first_published_at', 'Oldest to Newest')], default='-first_published_at', help_text='Choose the order in which to take results', max_length=20)),
                ('link_page', models.ForeignKey(blank=True, help_text='Use this to link to an internal page. Link to the page in the language of this menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('menu', modelcluster.fields.ParentalKey(help_text='Menu to which this item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='autofill_menu_items', to='menu.menu')),
            ],
            options={
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
