# Generated by Django 3.1.7 on 2021-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_auto_20210311_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuitem',
            name='title_of_submenu',
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='submenu_id',
            field=models.IntegerField(help_text='Select the sub-menu to load', null=True, verbose_name='Submenu'),
        ),
        migrations.AlterField(
            model_name='autofillmenuitem',
            name='menu_display_order',
            field=models.IntegerField(default=200, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number'),
        ),
        migrations.AlterField(
            model_name='autofillmenuitem',
            name='order_by',
            field=models.CharField(choices=[('-last_published_at', 'Newest (by most recently updated)'), ('-first_published_at', 'Newest to Oldest (by date originally published)'), ('first_published_at', 'Oldest to Newest')], default='-first_published_at', help_text='Choose the order in which to take results', max_length=20),
        ),
        migrations.AlterField(
            model_name='linkmenuitem',
            name='menu_display_order',
            field=models.IntegerField(default=200, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number'),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='menu_display_order',
            field=models.IntegerField(default=200, help_text='Enter digit to determine order in menu. Menu items of all types will be sorted by this number'),
        ),
    ]
