# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_remove_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofillmenuitem',
            name='include_linked_page',
            field=models.BooleanField(default=False, help_text='If selected, linked page will included before auto-filled items followed by dividing line', verbose_name='Include Linked Page in Menu'),
        ),
    ]
